sctb/lumen

bin/compiler.js
bin/compiler.lua
bin/reader.js
bin/reader.lua
bin/system.lua
compiler.l
reader.l

This PR fixes `LUMEN_HOST=node`. My earlier commit 435eb45 broke the node host in two different ways:
- I added the `literals` table into `reader.l`, causing `(read-string "toString")` to incorrectly return a `function` rather than `"toString"`:
```sh
$ LUMEN_HOST=node bin/lumen -e '((get (require "reader") "read-string") "toString")'
function
```
- I neglected to add `nan?` and `inf?` checks to `compile-atom`.  Since 435eb45 changed the reader to output literal `NaN` and `Infinity` rather than `"nan"` and `"inf"`, `compile-atom` therefore needed to check for those cases, just like it checks for `boolean?`.
```sh
$ LUMEN_HOST=node bin/lumen -e '(compile inf)'
"Infinity"
```
Sorry about that.  The root of the problem was that I was too reliant on unit tests.  I should have run `export …

LUMEN_HOST=node is broken.

---

bin/lumen

This PR fixes `bin/lumen` to allow spaces in `LUMEN_HOST`.
(For example, Numen (https://github.com/gruseom/numen) sets `LUMEN_HOST` to `node --expose_debug_as=v8debug`.)

bin/lumen: Let LUMEN_HOST contain spaces.

---

bin/reader.js
bin/reader.lua
reader.l
test.l

On `LUMEN_HOST=node`, `"0?"` is incorrectly read as `0`.  (As is `"0!"`, etc.)  This prevents users from e.g. making a macro named `0?`
This PR modifies `reader.l` in the following way:
- When reading a string, try to convert it to a number only if it ends with a
digit (i.e. ends with "0", "1", ..., or "9").
Note that `"0."` will now be read as `"0."`  If it should be read as `0`, let me know and I'll add a case to handle this.

reader.l: Fix (read-string "0?") to give "0?"

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
bin/reader.js
bin/reader.lua
compiler.l
macros.l
main.l
test.l

- The repl now prints a stacktrace along with error messages.
- The GUARD macro now yields (ok x trace)
Lua:
```
$ bin/lumen
> (let ((ok x trace) (guard (error "x"))) (print trace))
stack traceback:
[string "local __x6 = nil..."]:9: in function <[string "local __x6 = nil..."]:8>
[C]: in function 'error'
[string "local __x6 = nil..."]:5: in function <[string "local __x6 = nil..."]:4>
[C]: in function 'xpcall'
[string "local __x6 = nil..."]:4: in function 'f'
lumen/bin/compiler.lua:966: in function 'run'
lumen/bin/compiler.lua:977: in function 'eval'
lumen/bin/lumen.lua:941: in function <lumen/bin/lumen.lua:940>
[C]: in function 'xpcall'
lumen/bin/lumen.lua:940: in function 'eval_print'
lumen/bin/lumen.lua:982: in function 'rep1'
lumen/bin/lumen.lua:991: in function 'repl' …
```

Add stack traces to errors.

---

README.md

I was trying to make the README interactive and noticed a minor bug:
```
> (let a (1 2 3)
(quasiquote (9 8 (unquote-splicing a))))
```
This should be `'(1 2 3)` rather than `(1 2 3)`.

Minor README fix.

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
bin/reader.js
bin/reader.lua
bin/system.lua
compiler.l

I profiled Lumen during compilation and noticed that `getenv` was taking ~20% of total compilation time.  Unrolling the operations yielded the following gains during compilation:
```
LUMEN_HOST=node   ~15% faster
LUMEN_HOST=lua    ~25% faster
LUMEN_HOST=luajit ~20% faster
```
This improvement comes at the cost of clarity, so I'm not sure this PR should be accepted.  (However, if you add a macro like `rfor` (reverse `for`) then you'd get the clarity back.)

Optimize compilation speed.

---

makefile

This PR fixes `makefile` to allow spaces within `LUMEN_HOST`.
I discovered the recent `getenv` optimization by running LuaJIT 2.1's new profiler:
```
$ LUMEN_HOST="luajit -jp=s2" make -B
```
But in order to run that command, this PR was necessary.
I figured I should contribute the fix upstream before I forget about it.

makefile: Allow LUMEN_HOST to contain spaces.

---

README.md

There was a markdown rendering problem in the README due to an unescaped backtick.

Minor README.md fix.

---

README.md
bin/compiler.js
bin/compiler.lua
bin/reader.js
bin/reader.lua
bin/system.lua
reader.l

This PR restores Lumen's old dot syntax, which was previously removed in commit 6410c8cc2de.  It's an a minimalistic alternative to PR #51, and is intended to strictly restore the old dot syntax rather than provide additional flexibility.
String atoms that contain `.` but begin or end with `.` or contain `..` are ignored.
According to tests, this PR introduces no measurable slowdowns.

Dot syntax

---

bin/lumen.js
bin/lumen.lua
runtime.l
test.l

This PR reverts 9967ebc.
It's true that Lumen doesn't rely on SORT, but sorting is a pretty common operation. Would it be better idea to keep it?
(For what it's worth, I ended up needing SORT once or twice, e.g. when writing scripts to process text. It wasn't a big deal to add SORT myself, but new users probably won't be able to whip up a SORT that works on both lua and js. I figured I may as well send a PR to ask.)
The argument that SORT should be removed because it's unused by Lumen would also apply to SYSTEM.RELOAD, SYSTEM.GET-ENVIRONMENT-VARIABLE, etc. On the other hand, maybe it's best to remove all unused functions throughout the entire codebase rather than support a bunch of disparate convenience functions. How do you feel about it?

Define SORT

---

bin/lumen

This PR introduces support for creating symlinks to `bin/lumen`. Here are a few situations where this might be useful: 
- Installing `lumen` globally
```sh
$ git clone https://github.com/sctb/lumen
$ ln -s "$(pwd)/lumen/bin/lumen" /usr/local/bin/lumen
$ lumen -e 1
1
```
- Adding a `make install` target to Lumen's makefile
```make
PREFIX?=/usr/local
install: all
@mkdir -p "$(PREFIX)/bin"
@ln -sf "$(shell pwd)/bin/lumen" "$(PREFIX)/bin/lumen"
uninstall:
@rm -f "$(PREFIX)/bin/lumen"
```
```sh
$ make test && make install && lumen -e 1
js:
609 passed, 0 failed
lua:
609 passed, 0 failed
1
```
- Making Lumen available through Homebrew. `brew install lumen` could be pretty convenient.
Features:
1.  Symlinks containing relative paths are supported. E.g. Homebrew would install Lumen by creating a …

Support symlinks to bin/lumen

---

bin/compiler.lua
compiler.l

This PR allows lua5.1 to be used as a `LUMEN_HOST`.
Currently `LUMEN_HOST=lua5.1` results in an error:
```
$ LUMEN_HOST=lua5.1 lumen -e 1
error: bad argument #1 to 'load1' (function expected, got string)
```

Minor fix for Lua 5.1

---

bin/lumen

This PR adds `$(pwd)/node_modules` to NODE_PATH, allowing users to install a library from npm, then `require` it using Lumen.
This matches the expected behavior of Node. For example, using Node, try the following:
```
$ npm install leftpad
leftpad@0.0.0 node_modules/leftpad
$ node -e 'console.log(require("leftpad"))'
[Function]
```
Currently, Lumen doesn't support this:
```
$ LUMEN_HOST=node lumen -e '(require "leftpad")'
Error: Cannot find module 'leftpad'
```
Users would expect this to work, because it's the very basis of the Node ecosystem. It's also in line with Lumen's goal of matching the target runtime environment as closely as possible.
Initially I was confused why this wasn't working. Node's `require` algorithm should already be doing this. But it turns out that `require` tries …

Minor fix for npm

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
compiler.l

`+` compiles to `_43`, so it follows that `-` should compile to `_45`.
Currently `-` compiles to `_`. I'd like to be able to use `_` as a variable name without conflicting with Lumen's `-` function.

Prevent "-" from being compiled to "_"

---

test.l

It seems like the original intent of this test was to verify that `(let y nil |y = 10| 42)` correctly mutates `y`.
If so, then `(test= 10 x)` was a typo, and this PR fixes it.

Fix standalone test

---

bin/lumen.js
bin/lumen.lua
runtime.l
test.l

Prevent empty string keys from being converted to nan on JS.
Previously,
```
$ LUMEN_HOST=node bin/lumen
> (each (k v) (set-of "" "a")
(print k))
NaN
a
> (each (k v) (get (require 'reader) 'read-table)
(print (str (list k v))))
(nan function)
("(" function)
(")" function)
...
```

Minor fix in NUMERIC?

---

bin/lumen.js
bin/lumen.lua
runtime.l
test.l

Additionally, REDUCE now accepts an argument to be returned when given
an empty list.
cf. fe98c902

Fix`(apply * '(0 0)) and friends

---

bin/lumen.js
bin/lumen.lua
macros.l

This fixes an error when exporting "length" on JS when targeting Lua.
This allows JS hosts to export objects that contain a "length" property, such as Motor's buffer object.
Currently,
```
git clone https://github.com/sctb/motor
LUMEN_HOST=node lumen -c motor/buffer.l -t js
```
results in an error:
```
lumen/bin/lumen.js:201
r[_k2] = v;
^
RangeError: Invalid array length
at join (lumen/bin/lumen.js:201:16)
at Function.setenv.macro (lumen/bin/lumen.js:1138:23)
at apply (lumen/bin/lumen.js:627:12)
at expand1 (lumen/bin/compiler.js:284:16)
at expand_macro (lumen/bin/compiler.js:278:22)
at macroexpand (lumen/bin/compiler.js:307:24)
at map (lumen/bin/lumen.js:272:13)
at macroexpand (lumen/bin/compiler.js:309:28)
at Object.expand (lumen/bin/compiler.js:1051:16)
at compile_file …
```

Minor fix in EXPORT for JS

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
bin/reader.js
bin/reader.lua
bin/system.js
bin/system.lua
compiler.l
macros.l
runtime.l
test.l

Closes #80, #92.
This PR implements the strategy you proposed in #92. It also introduces a new special form, `%literal`, which compiles all of its arguments. See the `id` test:
```
(define-test id
(let (a 10
b (obj x: 20)
f (fn () 30))
(test= 10 a)
(test= 10 (%literal a))
(test= 20 (%literal b |.| x))
(test= 30 (%literal f |()|))))
```
`%literal` was introduced because e.g. `|#x|` is no longer valid when `x` is let-bound, and
```(when-compiling (cat "|#" (macroexpand 'x) "|"))```
is rather cumbersome.

Update LET to always bind to unique names

---

bin/compiler.js
compiler.l

`"toString"`, `"valueOf"`, etc were incorrectly being classified as reserved words on JS.
E.g. this was incorrect behavior:
```
$ LUMEN_HOST=node lumen -e "(compile 'toString)"
"_toString"
```
Correct behavior:
```
$ LUMEN_HOST=node lumen -e "(compile 'toString)"
"toString"
```
A more general fix would be to change the `set-of` macro to return an object without a prototype chain. Then `(let o (set-of "foo") (get o 'toString))` would return nil. (It currently returns a function.)

Fix RESERVED? on JS

---

README.md
bin/compiler.js
bin/compiler.lua
bin/reader.js
bin/reader.lua
reader.l
test.l

I changed my mind. I agree that Lumen doesn't need dot syntax. It interferes with using Lumen to implement support for other Lisps that use dots in ways that aren't necessarily equivalent to `(get a 'b)`.
Instead, I think it would be better to modify `compile-file` so that it reads an expression, expands it, reads the next expression, expands that, etc. That way it would be possible to write a Lumen file that modifies Lumen's reader at compile time, at the top of the file, within a `when-compiling` block.
At that point it'd be straightforward to write a user library that enables dot syntax by modifying `read-table`'s atom reader.

Remove dot syntax

---

bin/compiler.js
bin/compiler.lua
compiler.l
test.l

Closes #104.
This PR also defines a new global function `(infix-operator? x)` which returns `(and (obj? x) (infix? (hd x)))`.

Fix GET when the first argument is an infix op

---

bin/lumen.js
bin/lumen.lua
runtime.l
test.l

This PR introduces a new runtime function, `(either x y)`, which returns `(if (is? x) x y)`.
My recent change to `reduce` was a little awkward. It's strange for reduce to take an argument to be returned if the input list is empty. This PR reverts `reduce` to the previous version, while using `(either (reduce ...` in the appropriate places to maintain the existing fixes.
`either` is also useful in situations where you'd want to use `(if (is? x) x y)`. For example:
```
(define foo (x)
(set x (either x 42))
...)
```

Define EITHER

---

bin/lumen.lua
runtime.l
test.l

This PR fixes the following bug:
```
$ lumen -e "(str (with l () (set (get l (fn ())) true)))"
error: attempt to concatenate local 'k' (a function value)
```

Fix STR for tables with non-atom keys in Lua

---

bin/compiler.js
bin/compiler.lua
compiler.l
test.l

Closes #118.
This PR fixes the following test case on Lua hosts:
```
(test= 'b ((fn () (case 2 0 (do) 1 'a 2 'b))))
```
(Without this PR, `((fn () (case 2 0 (do) 1 'a 2 'b)))` incorrectly evaluates to `nil` on Lua.)

Minor fix in LOWER-STATEMENT

---

bin/compiler.js
bin/compiler.lua
compiler.l

This PR fixes the following bug:
```
> (print (compile (expand '(set (get l (cat "a" "b" "c")) 42))))
l["a" .. "b"] = 42
```
Previously, the first argument to `%set` wasn't being lowered, causing `(cat "a" "b" "c")` to be skipped rather than lowering it as `(cat (cat "a" "b") "c")`.

Minor fix in LOWER-SET

---

bin/compiler.js
bin/compiler.lua
compiler.l
test.l

Closes #129.
Update `valid-id?` to reflect the fact that identifiers which start with numbers aren't valid.

Minor fix in VALID-ID?

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
compiler.l
runtime.l

Lumen redefines LOAD/EVAL, which are standard functions in Lua/JS.
HOST stores their original definitions.
Closes #76.

Define HOST

---

makefile

This PR introduces support for `make install` and `make uninstall`.
1. Running `make install` will symlink `/usr/local/bin/lumen -> $(pwd)/bin/lumen`
2. Running `LUMEN_NAME=sctb-lumen make install` will symlink `/usr/local/bin/sctb-lumen -> $(pwd)/bin/lumen`
3. Running `PREFIX=~/bin LUMEN_NAME=sctb-lumen make install` will symlink `~/bin/sctb-lumen -> $(pwd)/bin/lumen`
In the above examples, replacing `make install` with `make uninstall` would delete the corresponding symlink.
This PR makes it much easier to have several different versions of Lumen installed simultaneously. Personally, I have `sctb-lumen` which points to the latest commit in your repository, `lumen-experimental` which points to my work-in-progress version of lumen, and `lumen-old` which points to a version of lumen from …

Add install/uninstall commands to the makefile

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
compiler.l
runtime.l

Since `eval` is now a reserved word, `host` is no longer needed on JS. This PR makes `host` no longer needed at all.
Alternatively, I could remove `host.eval` and leave `host.load` alone.

Make "load" a reserved word; get rid of HOST

---

bin/compiler.js
bin/compiler.lua
compiler.l

Returning a call to a function that returns multiple values will now correctly return all of those values.
For example, `xpcall` returns multiple values:
```
> (list (xpcall (fn () (error 'foo)) (fn (m) m)))
(false "[string \"_37result = {xpcall(function ()...\"]:2: foo")
```
Without this PR, returning a call to `xpcall` will only give the first value:
```
> (define-global xpcall* (f err) (xpcall f err))
> (list (xpcall* (fn () (error 'foo)) (fn (m) m)))
(false)
```
After this PR, returning a call to `xpcall` will correctly give all the values:
```
> (define-global xpcall* (f err) (xpcall f err))
> (list (xpcall* (fn () (error 'foo)) (fn (m) m)))
(false "[string \"_37result = {xpcall42(function ()...\"]:2: foo")
```

Fix RETURN for multiple values on Lua

---

bin/compiler.js
bin/compiler.lua
bin/lumen.js
bin/lumen.lua
compiler.l
macros.l

An expression like `(%call f x)` becomes `(f x)` during lowering.
This is useful for macros that return a call to a function or infix operator with an identical name.

Lower %CALL

---

bin/compiler.js
bin/compiler.lua
compiler.l

Consider the following special form:
```
(define-special await (x)
(cat "await " (compile x)))
```
Without this pull request, this will give incorrect indentation:
```
(define-global foo (x)
(print 1)
(await x)
(print 2))
```
```js
foo = function (x) {
print(1);
await x;
return print(2);
};
```
Note that `await x;` isn't indented.
This pull request fixes indentation of non-`:stmt` special forms when used as a statement (such as the above example).

Indent non-statement special forms properly

---

bin/lumen.js
bin/lumen.lua
macros.l
test.l

I noticed that `let-macro` and `let-symbol` don't expand their body correctly. This PR fixes that, and adds tests to illustrate the problem.

Fix LET-MACRO and LET-SYMBOL

---

bin/compiler.js
bin/compiler.lua
compiler.l

Similar to #228, this PR fixes expansion of function and definition bodies.
e.g. `(macroexpand '(%function (x) let y x y))` currently treats `let y x y` as an expression `(let y x y)` rather than separate expressions `let`, `y`, `x`, and `y`. Ditto for `%local-function` and `%global-function`.
It'd be hard to run into this bug in practice (you'd have to use `%function` expressions without using `bind*`), but it's probably worth fixing if only to demonstrate to new users the correct way to expand a list of expressions.

Fix body expansion

---

test.l

I think the tests were clearer prior to #228, so this PR removes them:
```
(test= '(do (do a 42))
(macroexpand '(let-macro ((a (x) `(+ ,x 1)))
(let-symbol (b 42) a b))))
(test= '(do a 42)
(macroexpand '(let-macro ((a (x) `(+ ,x 1))) a 42)))
```
I introduced those mostly to explain the bug I was trying to fix, rather than to ensure the bug doesn't happen again.
Those tests also make it more difficult to change the implementations of `let-macro` and `let-symbol`, because they force implementations to expand into ``` `(do ,@body) ```. (For example, an alternative implementation is to check if`(one? body)` is true, and if so, return`(hd body)`, else return ``` `(do ,@body)```. With the current tests, this implementation would be disallowed, even though it's a valid way of simplifying body …

Simplify tests
